% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Tarea 3 LaTex, R y Markdown},
  pdfauthor={Bryan Morales},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Tarea 3 LaTex, R y Markdown}
\author{Bryan Morales}
\date{18/3/2021}

\begin{document}
\maketitle

\hypertarget{pregunta-1}{%
\subsection{Pregunta 1}\label{pregunta-1}}

Realiza los siguiente productos de matrices siguiente en R:

\[
  A \cdot B
\]

\[
  B \cdot A
\]

\[
  (A \cdot B)^{t}
\]

\[
  B^t \cdot A
\]

\[
  (A\cdot B)^{-1}
\]

\[
  A^{-1} \cdot B^t
\]

Finalmente, escribe haciendo uso de \LaTeX{} el resultado de los
primeros productos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{A =}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{0}\NormalTok{)) }\CommentTok{# Creamos la primera matriz A}

\NormalTok{B =}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{)) }\CommentTok{# Creamos la segunda matriz B}

\CommentTok{# Calculamos el primer producto}
\NormalTok{A}\OperatorTok{%*%}\NormalTok{B }\CommentTok{# Producto matricial}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    7   19   11   29
## [2,]   18   26   14   26
## [3,]    0    5    0    8
## [4,]   16   17   18   19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{B}\OperatorTok{%*%}\NormalTok{A}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]   19   19   22   23
## [2,]   24    9   22    3
## [3,]   21   11   23   12
## [4,]   10    3   10    1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t}\NormalTok{(A}\OperatorTok{%*%}\NormalTok{B) }\CommentTok{# Transpuesta de producto matricial}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    7   18    0   16
## [2,]   19   26    5   17
## [3,]   11   14    0   18
## [4,]   29   26    8   19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{solve}\NormalTok{(A}\OperatorTok{%*%}\NormalTok{B) }\CommentTok{# Inversa del producto matricial}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       [,1]  [,2]  [,3]  [,4]
## [1,] -1.66 -0.65  4.52  1.52
## [2,]  1.60  0.80 -4.60 -1.60
## [3,]  1.02  0.35 -2.84 -0.84
## [4,] -1.00 -0.50  3.00  1.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{solve}\NormalTok{(A)}\OperatorTok{%*%}\KeywordTok{t}\NormalTok{(B) }\CommentTok{# Una operación un poco más compleja}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               [,1] [,2] [,3] [,4]
## [1,]  6.000000e-01  2.4  6.4  1.2
## [2,] -3.330669e-16 -2.0 -7.0 -1.2
## [3,] -2.000000e-01 -0.8 -3.8 -0.4
## [4,]  1.000000e+00  1.0  5.0  0.6
\end{verbatim}

Escribiendo los dos primeros resultados en \LaTeX{} nos queda de la
siguiente forma:

\[
  A\cdot B = 
  \begin{pmatrix}
  7 &  19 &  11 &  29 \\
  18  & 26  & 14  & 26\\
  0   & 5 &   0 &   8\\
  16  & 17  & 18  & 19\\
  \end{pmatrix}
\]

El segundo resultado que nos da es:

\[
  B \cdot A =
  \begin{pmatrix}
    19 &  19  & 22  & 23\\
    24  &  9  & 22  &  3\\
    21  & 11  & 23  & 12\\
    10  &  3 &  10  &  1\\
  \end{pmatrix}
\]

\hypertarget{pregunta-2}{%
\subsection{Pregunta 2}\label{pregunta-2}}

Considera en un vector los números de tu DNI. Define el vector en R,
cacula el cuadrado, la raíz cuadrada y, por último, la suma de todas las
cifras del vector.

Finalmente escribe todos estos vectores en LaTeX

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dni =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{7}\NormalTok{) }\CommentTok{# Este es el dni}
\NormalTok{dni_cuadrado =}\StringTok{ }\NormalTok{dni}\OperatorTok{**}\DecValTok{2}
\NormalTok{dni_cuadrado}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 16 81 64 25 81  9  4  1 81 49
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dni_sqrt =}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(dni) }\CommentTok{# Calculamos la raíz cuadrada del dni}
\NormalTok{dni_sqrt}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 2.000000 3.000000 2.828427 2.236068 3.000000 1.732051 1.414214 1.000000
##  [9] 3.000000 2.645751
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dni_sum =}\StringTok{ }\KeywordTok{sum}\NormalTok{(dni) }\CommentTok{# Suma del vector dni}
\NormalTok{dni_sum}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 57
\end{verbatim}

Escritos en \LaTex{} serían de la siguiente forma

\[
  dni = (4,9,8,5,9,3,2,1,9,7)
\]

\[
  dni^2 = (16, 81, 64, 25, 81,  9,  4,  1, 81, 49)
\]

\[
  \sqrt{dni} = (2.000000, 3.000000, 2.828427, 2.236068, 3.000000, 1.732051, 1.414214, 1.000000, 3.000000, 2.645751)
\]

\[
  \sum_{i=1}^{N} dni = 57
\]

\hypertarget{pregunta-3}{%
\section{Pregunta 3}\label{pregunta-3}}

Considera un vector con tu nombre y apellido. Define dicho vector en R,
calcula el subvector que solo tenga tu nombre, calcula el subvector que
solo tenga tu apellido, y ordenalo alfabéticamente, crea una matriz con
este vector.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mi_nombre =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{,}\StringTok{"R"}\NormalTok{,}\StringTok{"Y"}\NormalTok{,}\StringTok{"A"}\NormalTok{,}\StringTok{"N"}\NormalTok{,}\StringTok{"M"}\NormalTok{,}\StringTok{"O"}\NormalTok{,}\StringTok{"R"}\NormalTok{,}\StringTok{"A"}\NormalTok{,}\StringTok{"L"}\NormalTok{,}\StringTok{"E"}\NormalTok{,}\StringTok{"S"}\NormalTok{)}
\NormalTok{nombre =}\StringTok{ }\NormalTok{mi_nombre[}\DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{] }\CommentTok{# Calculamos el nombre}
\NormalTok{nombre}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "B" "R" "Y" "A" "N"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{apellido =}\StringTok{ }\NormalTok{mi_nombre[}\DecValTok{6}\OperatorTok{:}\KeywordTok{length}\NormalTok{(mi_nombre)] }\CommentTok{# Este es el apellido}
\NormalTok{apellido}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "M" "O" "R" "A" "L" "E" "S"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sort}\NormalTok{(apellido)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "A" "E" "L" "M" "O" "R" "S"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{matrix}\NormalTok{(nombre,}\DataTypeTok{nrow=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in matrix(nombre, nrow = 2): la longitud de los datos [5] no es un
## submúltiplo o múltiplo del número de filas [2] en la matriz
\end{verbatim}

\begin{verbatim}
##      [,1] [,2] [,3]
## [1,] "B"  "Y"  "N" 
## [2,] "R"  "A"  "B"
\end{verbatim}

\end{document}
